version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: disasters
      MONGO_INITDB_ROOT_PASSWORD: disasters_pass
      MONGO_INITDB_DATABASE: disasters_test
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://disasters:disasters_pass@mongo:27017/disasters_test?authSource=admin
      - NODE_ENV=test
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - .:/usr/src/app
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api-docs']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  mongo_data:
